/* Noir Balance · conocimiento a fondo: deudas, videografía/agencia, SAT, inversión y metas (información general) */
(function () {
  const NB = window.NB;
  const E = (id, g, t, k, a) => ({ id, g, t, k, a: Array.isArray(a) ? a : [a] });
  const more = [
    /* ===== DEUDAS Y TARJETAS ===== */
    E('d-orden-pago', 'fin', '¿En qué orden pago varias deudas?', '!orden varias deudas pagar cual primero prioridad muchas tarjetas', ['Regla práctica: 1) paga **mínimos o lo requerido** de todas a tiempo, 2) el dinero extra va a la de **mayor tasa** (o a la más chica si necesitas motivación), 3) cuando liquides una, su pago se suma a la siguiente (efecto bola de nieve).', 'Dime "estrategia" y la armo con tus montos y fechas reales.']),
    E('d-interes-calculo', 'fin', '¿Cómo se calculan los intereses de la tarjeta?', '!calculan calculo interes tarjeta como se cobran saldo promedio diario tasa 12', ['Aproximadamente: saldo × tasa anual ÷ 12 por mes (a veces calculado diario), más **IVA** sobre los intereses. Si pagas el total antes de la fecha límite, no pagas intereses por compras.']),
    E('d-saldo-revolvente', 'fin', '¿Qué es el saldo revolvente?', '!revolvente saldo revolvente arrastrar deuda anterior no liquidado', ['Es la parte de tu deuda que no pagas en el mes y se "arrastra" generando intereses. Una vez que tienes revolvente, las **compras nuevas también generan interés** desde el día de la compra.']),
    E('d-pago-extra', 'fin', '¿Conviene dar pagos extra a un préstamo?', '!pago extra adelantado anticipado abono capital prestamo liquidar antes', ['Normalmente sí: un abono a **capital** reduce el saldo y los intereses futuros. Confirma que no haya penalización por pago anticipado y especifica que el abono sea a capital, no a "adelantar mensualidades".']),
    E('d-refinanciar', 'fin', '¿Qué es refinanciar o reestructurar una deuda?', '!refinanciar reestructurar reestructura cambiar condiciones plazo nueva deuda renegociar', ['Es cambiar las condiciones (plazo, tasa) de una deuda. Puede bajar tu mensualidad, pero **alargar el plazo suele aumentar el total de intereses**. Compara el CAT antes y después.']),
    E('d-transferencia-saldo', 'fin', '¿Sirve transferir saldo a otra tarjeta con menos tasa?', '!transferir transferencia saldo otra tarjeta menor tasa traspaso promocion', ['Puede servir si la nueva tasa es mucho menor y no te cobran comisión alta. Calcula el **costo total** y evita volver a usar la tarjeta vieja, o terminas con más deuda.']),
    E('d-prestamo-personal', 'fin', '¿Conviene un préstamo personal para pagar tarjetas?', '!prestamo personal pagar tarjetas consolidar nomina credito personal liquidar', ['Si su **CAT es menor** al de tus tarjetas y de verdad dejas de usarlas, baja tus intereses y ordena tus pagos. Si no cambias el hábito, te quedas con dos deudas. Compara CAT, comisiones y plazo.']),
    E('d-embargo', 'fin', '¿Me pueden embargar por una deuda de tarjeta?', '!embargo embargar demanda juicio bienes cobranza judicial tarjeta', ['Un embargo requiere un **juicio y orden de un juez**; no pueden quitarte nada por llamadas. Aun así no ignores la deuda: negocia antes. Si te llega una demanda real, busca un abogado o apoyo en CONDUSEF.']),
    E('d-prescribe', 'fin', '¿Las deudas prescriben?', '!prescribe prescripcion deuda caduca olvida anos tiempo borrar buro', ['Las deudas pueden prescribir con el tiempo según su tipo, y el Buró borra registros tras ciertos años, pero las reglas son técnicas. Consulta a un abogado o a CONDUSEF antes de dar por perdida una deuda.']),
    E('d-fecha-corte-estrategia', 'fin', '¿Conviene comprar justo después de la fecha de corte?', '!despues corte comprar compras estrategia dias sin intereses periodo maximo', ['Sí: una compra justo después del corte te da el **máximo plazo sin intereses** (hasta ~50 días) si pagas el total. Pero solo funciona si pagas el total siempre.']),
    E('d-cat-comparar', 'fin', '¿Cómo comparo dos créditos?', '!comparar creditos dos ofertas cat cual conviene mejor credito tasa comisiones', ['Usa el **CAT** (incluye intereses y comisiones), el plazo y el **pago total** al final. El crédito con mensualidad más baja no siempre es el más barato.']),
    E('d-limite-uso', 'fin', '¿Cuánto de mi límite debería usar?', '!cuanto limite usar porcentaje utilizacion 30 maximo tarjeta saldo limite', ['Idealmente **menos de 30%** de tu límite; menos de 10% es excelente. Si usas 60% o más, tu historial y tu tranquilidad se resienten. Pregúntame "mis tarjetas" y te digo tu uso actual.']),
    E('d-pago-doble', 'fin', '¿Conviene pagar la tarjeta en dos partes?', '!pagar dos partes quincenal fraccionar pagos tarjeta antes corte', ['Sí, pagar en 2 o 3 abonos durante el mes ayuda a no acumular y baja el saldo que el banco reporta. Lo importante es que el total llegue antes de la fecha límite.']),
    E('d-bnpl', 'fin', '¿Qué son los pagos en parcialidades de apps (Kueski, Aplazo)?', '!kueski aplazo mercado pago comprar ahora pagar despues parcialidades bnpl quincenas', ['Son créditos cortos para compras. Pueden salir **muy caros** si te atrasas y suman pagos que olvidas. Regístralos como préstamo en la app para que aparte desde ahora.']),
    E('d-credito-nomina', 'fin', '¿Un crédito de nómina me sirve siendo freelance?', '!nomina credito freelance independiente banco prestamo sin nomina como pedir', ['Sin nómina los bancos piden **estados de cuenta con depósitos** e historial. Mantener tus cobros en una sola cuenta durante varios meses te abre puertas a mejores tasas.']),

    /* ===== VIDEOGRAFÍA / AGENCIA ===== */
    E('v-cotizar-video', 'free', '¿Cómo cotizo un video o producción?', '!cotizar video produccion cotizacion reel comercial proyecto audiovisual cuanto cobrar edicion', ['Desglosa: **preproducción** (guion, locaciones), **rodaje** (jornada, equipo, traslados), **postproducción** (edición, color, audio, motion), licencias y revisiones. Suma costos + tu margen (30% o más) + imprevistos (10%).', 'Cotiza por **entregable** (ej. "reel de 30 s") y por paquetes; evita cobrar solo por hora.']),
    E('v-jornada', 'free', '¿Cuánto cobrar por día de rodaje?', '!jornada !rodaje !filmacion dia tarifa diaria cobro dia filmacion cobrar por dia', ['Calcula tu **costo por día** (tus gastos del mes + impuestos + ahorro ÷ días facturables reales, unos 8 a 12 al mes) y súmale el equipo. Cobra más por jornadas largas, nocturnas o urgentes.']),
    E('v-dias-facturables', 'free', '¿Qué son los días facturables?', '!dias facturables horas facturables productividad no todo es trabajo pagado administrativo', ['No todo tu tiempo se cobra: hay prospectar, administrar y descansar. Si trabajas 20 días al mes, quizá solo **10 a 12 son facturables**. Tu tarifa debe cubrir los demás.']),
    E('v-renta-equipo', 'free', '¿Conviene rentar o comprar equipo de video?', '!rentar !renta comprar equipo video camara lente luces renta casa renta conviene', ['Si lo usarías **menos de 6 a 8 veces al año**, rentar suele salir mejor. Si lo usas cada mes y se paga solo con 1 o 2 proyectos, compra. Cobra la renta del equipo a tu cliente si es propio.']),
    E('v-cobrar-equipo', 'free', '¿Cobro aparte el uso de mi equipo?', '!cobrar uso equipo propio aparte renta equipo cliente tarifa equipo incluido', ['Sí, conviene: una "renta de equipo" por jornada ayuda a **recuperar y reponer** tu inversión (cámara, lentes, luces). Puede ir como línea separada o incluida en el paquete.']),
    E('v-derechos', 'free', '¿Qué derechos de uso cobro por mi video?', '!derechos uso licencia cesion autoral publicidad exclusividad cliente video propiedad', ['El cliente paga la producción; el **uso** (dónde y cuánto tiempo se publica) puede cobrarse aparte: redes, TV, anuncios pagados, exclusividad. Escríbelo en el contrato. Para asuntos autorales, consulta a un abogado.']),
    E('v-pagar-editor', 'free', '¿Cuánto pago a un editor o asistente?', '!editor !asistente !camarografo pagar editor asistente camarografo freelance colaborador cuanto pagar equipo produccion', ['Fija un pago por **entregable o jornada** y acuérdalo antes. Como guía, que el costo de colaboradores no pase del 30 a 40% de lo que cobras al cliente para mantener un margen sano.']),
    E('v-margen-proyecto', 'free', '¿Cómo sé si un proyecto me dejó ganancia?', '!ganancia proyecto margen rentable fue rentable cuanto gane proyecto costos reales', ['Resta al cobro: colaboradores, renta, traslados, software y **tu tiempo**. Anota cada gasto con la nota del proyecto en la app para verlos juntos con la búsqueda.']),
    E('v-agencia-flujo', 'free', '¿Cómo organizo el dinero de mi agencia (Noir)?', '!agencia noir flujo dinero organizar negocio ingresos egresos cuentas empresa estudio', ['1) Todo cobro entra a la cuenta del negocio. 2) Separa **impuestos** y **ahorro**. 3) Paga colaboradores y herramientas. 4) Transfiérete un **sueldo fijo**. Lo que sobra reinvierte o ahorra en meta.']),
    E('v-retainer', 'free', '¿Cómo ofrezco una iguala de contenido para redes?', '!iguala !retainer !redes contenido redes mensual social media paquete community manager', ['Define entregables por mes (ej. 8 posts, 4 reels, reporte), número de revisiones, fechas de entrega y pago por adelantado mensual. Una iguala te da **ingreso predecible**.']),
    E('v-presupuesto-cliente', 'free', '¿Qué hago si el cliente dice que mi precio es caro?', '!caro precio negociar cliente descuento regatear barato presupuesto menor', ['No bajes el precio, **ajusta el alcance**: menos entregables, menos revisiones o menos días. Enfoca la conversación en valor y resultados. Descuentos solo a cambio de algo (pago adelantado, volumen).']),
    E('v-urgente', 'free', '¿Cobro más por trabajos urgentes?', '!urgente prisa rapido fin de semana recargo express entrega rapida cobrar mas', ['Sí: un **recargo del 25% al 50%** por urgencias, fines de semana o entregas exprés es normal. Déjalo escrito en la cotización.']),
    E('v-gastos-hormiga-prod', 'free', '¿Qué gastos olvido en una producción?', '!olvido gastos produccion traslados comida estacionamiento baterias tarjetas memoria almacenamiento imprevistos', ['Traslados, comida del equipo, estacionamientos, baterías, tarjetas de memoria, almacenamiento, licencias de música, renta de locación y permisos. Suma un **10% de imprevistos** a toda cotización.']),
    E('v-almacenamiento', 'free', '¿Cuánto debo invertir en respaldos de mis proyectos?', '!respaldo almacenamiento disco duro nube proyectos archivos perder material backup video', ['Es un gasto de trabajo importante: perder un proyecto cuesta más que un disco extra. Regla 3-2-1: **3 copias, 2 medios distintos, 1 fuera de tu casa**. Anota el gasto como herramienta de trabajo.']),
    E('v-meses-flojos-video', 'free', '¿Cómo manejo meses flojos en video y redes?', '!meses flojos video redes vacacion enero verano pocos proyectos temporadas bajas', ['Planea con anticipación: guarda en tus meses fuertes, ofrece **paquetes recurrentes**, produce contenido propio y usa el tiempo libre para prospectar. Pregúntame "propón una meta" para ver tus semanas ligeras.']),

    /* ===== SAT / IMPUESTOS (INFORMACIÓN GENERAL) ===== */
    E('s-regimenes', 'free', '¿Qué regímenes fiscales puede tener un freelance?', '!regimen regimenes fiscal fiscales honorarios actividad empresarial resico plataformas cual me conviene', ['Los más comunes para independientes: **servicios profesionales (honorarios)**, **actividad empresarial** y **RESICO** (si cumples los requisitos). Cada uno cambia cómo calculas y pagas impuestos.', 'Elegir bien depende de tus ingresos y gastos; un contador te dice cuál te conviene.']),
    E('s-resico-requisitos', 'free', '¿Quién puede estar en RESICO?', '!resico requisitos quien puede limite ingresos tope anuales tasas persona fisica', ['Personas físicas con ingresos anuales **hasta un tope** (que el SAT fija) y que cumplan algunas condiciones. Tiene tasas bajas de ISR sobre lo cobrado, pero limita deducciones. Verifica el tope actual y si aplicas en el portal del SAT.']),
    E('s-pago-provisional', 'free', '¿Qué es un pago provisional?', '!provisional pago mensual adelanto isr pagos provisionales mes declaracion mensual', ['Es el pago de ISR que haces **cada mes** como adelanto de tu impuesto anual. Se calcula con tus ingresos (y gastos, según tu régimen). Se presenta normalmente a más tardar el día 17 del mes siguiente.']),
    E('s-declaracion-anual', 'free', '¿Cuándo es la declaración anual?', '!declaracion anual abril cuando presentar declarar año fiscal fecha anual personas fisicas', ['Las personas físicas la presentan en **abril** del año siguiente. Se compara lo que pagaste con lo que debías: puedes tener saldo a favor o a pagar. Un contador evita errores.']),
    E('s-deducciones-personales', 'free', '¿Qué son las deducciones personales?', '!deducciones personales medicos dentista colegiaturas seguro gastos medicos intereses hipotecarios anual', ['Gastos personales deducibles en la declaración anual: honorarios médicos y dentales, seguros de gastos médicos, intereses hipotecarios reales, aportaciones a retiro, donativos y otros, **con factura a tu nombre y pagados por medios electrónicos** (con ciertos límites).']),
    E('s-pago-efectivo', 'free', '¿Se puede deducir pagando en efectivo?', '!efectivo deducir deduccion pagar efectivo limite 2000 tarjeta transferencia comprobante', ['Los gastos pagados en efectivo suelen tener un límite para deducirse (históricamente alrededor de $2,000). Lo mejor: paga con **tarjeta o transferencia** y pide factura.']),
    E('s-factura-cancelar', 'free', '¿Cómo cancelo o corrijo una factura?', '!cancelar corregir factura error cfdi nota credito sustituir equivocada', ['Se cancela desde el portal o programa con el que facturas, normalmente con **aceptación del cliente** si ya pasó cierto monto o tiempo. Para correcciones suele hacerse una factura de sustitución. Pregunta a tu contador.']),
    E('s-complemento-pago', 'free', '¿Qué es el complemento de pago?', '!complemento pago ppd pue factura parcialidades diferido forma pago cfdi', ['Cuando facturas con pago **diferido o en parcialidades** (PPD), debes emitir un complemento de pago cuando recibes el dinero. Si te pagan de contado (PUE), no. Confirma el método con tu contador.']),
    E('s-multas', 'free', '¿Qué pasa si no declaro a tiempo?', '!multa !multas !recargos !declaro no declarar declaro atrasado sat omiso extemporanea sancion', ['Se generan **recargos y multas**. Declarar tarde, aunque sea sin pago, suele salir más barato que no declarar. Si te atrasaste, ponte al corriente cuanto antes con un contador.']),
    E('s-ingresos-sin-declarar', 'free', '¿Mis depósitos del banco los ve el SAT?', '!depositos banco sat ve revisa cuenta bancaria depositos efectivo informacion fiscal', ['Los bancos reportan al SAT ciertos depósitos en efectivo y movimientos relevantes. Lo seguro es que tus ingresos reales estén **facturados y declarados**, y llevar tus gastos con comprobante.']),
    E('s-iva-acreditable', 'free', '¿Qué es el IVA acreditable?', '!iva acreditable acreditar pagado gastos descontar restar iva a favor', ['Es el IVA que **pagas en tus gastos del negocio** (con factura) y que puedes restar al IVA que cobraste a tus clientes. Si el IVA cobrado es mayor, pagas la diferencia; si es menor, tienes saldo a favor.']),
    E('s-saldo-favor', 'free', '¿Qué es un saldo a favor?', '!saldo favor devolucion sat devuelven impuestos pagaste de mas devolver', ['Es cuando pagaste más impuestos de los necesarios. Puedes **pedir la devolución** o compensarlo con pagos futuros. La devolución puede tardar semanas; presenta bien tus datos bancarios.']),
    E('s-gasto-negocio-personal', 'free', '¿Puedo deducir gastos que son mixtos (casa, internet, celular)?', '!mixto casa internet celular luz renta casa oficina home office gasto mixto deducir proporcional', ['Solo la parte **estrictamente indispensable** para tu actividad y con factura a tu nombre; algunos conceptos tienen reglas especiales. Es una zona donde conviene preguntar a tu contador.']),
    E('s-ahorrar-impuestos-mes', 'free', '¿Cuánto debo tener listo cada mes para impuestos?', '!cada mes listo impuestos pago mensual cuanto reservar sat mes iva isr guardar fondo fiscal', ['Reserva un % de cada cobro (referencia: 10% a 30%, más el 16% de IVA si lo cobras). Al llegar el día 17, ya tienes el dinero separado. Ajusta el % cuando tu contador te dé tu número real.']),
    E('s-persona-moral', 'free', '¿Me conviene abrir una empresa (persona moral)?', '!persona moral empresa sa de cv sas abrir constituir agencia sociedad persona fisica', ['Una sociedad da separación legal, imagen y manejo de socios, pero implica **más costos y obligaciones** (contabilidad, declaraciones). Muchos empiezan como persona física y pasan a empresa cuando facturan más o buscan clientes corporativos.']),

    /* ===== INVERSIÓN Y AHORRO ===== */
    E('i-cetes-directo', 'fin', '¿Cómo compro CETES?', '!cetes !cetesdirecto comprar como invertir gobierno plazo 28 91 182 364 bajo riesgo', ['Puedes comprarlos en **CETESDirecto** o en tu banco/casa de bolsa. Hay plazos de 28 a 364 días; el rendimiento depende de la tasa de subasta. Son de bajo riesgo porque los respalda el gobierno.']),
    E('i-fondos-indexados', 'fin', '¿Qué es un fondo indexado o ETF?', '!fondo !etf !indexado indexado etf indice sp500 bolsa diversificar inversion pasiva comisiones', ['Es una canasta de muchas acciones que sigue un índice. Diversifica y cobra **comisiones bajas**. Es de riesgo medio a alto y se hace pensando a **largo plazo** (5+ años).']),
    E('i-interes-cuenta', 'fin', '¿Conviene dejar dinero en la cuenta del banco?', '!cuenta banco dejar dinero rendimiento interes cuenta debito inflacion dinero parado', ['Una cuenta normal rinde casi nada y la inflación se come tu dinero. Para tu **colchón**, busca una cuenta con rendimiento líquido o CETES; para lo que gastarás este mes, la cuenta normal está bien.']),
    E('i-plazo-horizonte', 'fin', '¿Para qué plazo invierto cada cosa?', '!plazo horizonte invertir corto largo meses anos cuando necesito dinero objetivo', ['Para dinero que necesitas en **menos de 1 año**: cuentas o CETES. De **1 a 3 años**: mezcla conservadora. De **5+ años**: puedes tomar más riesgo (fondos indexados). Nunca inviertas en riesgo lo que necesitas pronto.']),
    E('i-meta-alta', 'fin', '¿Cómo ahorro para una compra grande en pocas semanas?', '!meta alta compra grande ahorro rapido pocas semanas inversion equipo juntar rapido', ['Define el monto y la fecha, y reparte el ahorro **en tus semanas más ligeras** en vez de en partes iguales. Pregúntame "propón una meta de ahorro" y calculo cuándo te sobra más con tus cobros y pagos.']),
    E('i-capital-trabajo', 'fin', '¿Reinvierto en mi negocio o ahorro?', '!reinvertir negocio ahorrar invertir equipo marketing capacitacion agencia crecer retorno', ['Reinvierte cuando haya un **retorno claro** (equipo que permite cobrar más, formación, marketing que trae clientes). Antes, cubre deudas caras y tu colchón. Una buena proporción: 60% estabilidad, 30% crecimiento, 10% gustos.']),
    E('i-regla-72', 'fin', '¿Qué es la regla del 72?', '!regla 72 duplicar dinero cuanto tarda duplicar inversion tasa anos', ['Divide 72 entre la tasa anual para estimar en cuántos años se **duplica** tu dinero. Con 8% anual: 72 ÷ 8 = 9 años. También sirve para deudas: con 36% de interés, tu deuda se duplica en ~2 años.']),
    E('i-aportacion-automatica', 'fin', '¿Conviene automatizar mi ahorro?', '!automatizar automatico ahorro programado domiciliar transferir cada semana constante habito', ['Sí. Ahorrar apenas llega el dinero, sin decidir cada vez, es el hábito que más funciona. En la app, tu % de ahorro se aparta en **cada reparto**; refuérzalo con una transferencia semanal a una cuenta aparte.']),
    E('i-retiro-freelance', 'fin', '¿Cómo me preparo para el retiro siendo independiente?', '!retiro jubilacion pension independiente freelance futuro vejez afore voluntaria plan', ['Nadie lo hará por ti: aporta de forma **constante** a tu Afore (voluntarias), a un plan personal de retiro o a inversiones de largo plazo. Empezar con 3% a 5% de tus ingresos ya hace diferencia por el tiempo.']),
    E('i-ahorro-sobres', 'fin', '¿Qué es el método de los sobres?', '!sobres metodo efectivo categorias limite gasto sobre dinero fisico presupuesto cash', ['Asignas un monto por categoría (comida, gasolina, gustos) y cuando se acaba, **no gastas más** en ella. Es lo mismo que los **límites por categoría** en la app, pero sin sobres físicos.']),
    E('i-minimo-vivible', 'fin', '¿Qué es mi "mínimo vivible"?', '!minimo vivible gasto minimo sobrevivir basico cuanto necesito esenciales fijos', ['Es lo mínimo que necesitas al mes para vivir (renta, servicios, comida, deudas, herramientas). Conocerlo te dice cuánto colchón necesitas y qué recortar si baja el trabajo.']),
    E('i-objetivo-colchon-freelance', 'fin', '¿Cuánto colchón me falta?', '!falta colchon cuanto me falta meses aguanto fondo emergencia objetivo calcular', ['Colchón objetivo = tu mínimo vivible × 3 a 6 meses. Pregúntame **"¿cuánto aguanto?"** y comparo tu ahorro con tus gastos reales.'])
  ];
  NB.KB = (NB.KB || []).concat(more);
})();
