/* Noir Balance · base de conocimientos del Asesor
   k: palabras clave ('!' = clave fuerte). t: pregunta tipo. a: respuesta (líneas). */
(function () {
  const NB = window.NB;
  NB.KB = [
    /* ===== CÓMO USAR LA APP ===== */
    { id: 'cliente-add', g: 'app', t: '¿Cómo agrego un cliente?', k: '!cliente !clientes agregar crear nuevo anadir registrar dar alta', a: ['Ve a **Ajustes > Clientes > Agregar cliente**.', 'Pon su nombre, el monto aproximado y cada cuánto paga: cada semana (eliges el día), cada 2 semanas (eliges una fecha de pago) o cada mes (eliges el día del mes).', 'El monto puede variar: al confirmar cada pago lo ajustas.'] },
    { id: 'cliente-edit', g: 'app', t: '¿Cómo pauso, edito o borro un cliente?', k: '!cliente !clientes pausar pausa editar borrar eliminar quitar cambiar dia monto', a: ['Entra a **Ajustes > Clientes**. Ahí puedes pausar o reanudar a cada cliente, editar su día y monto, o eliminarlo.', 'Un cliente en pausa deja de avisarte y de contar como ingreso esperado.'] },
    { id: 'cliente-pago', g: 'app', t: '¿Qué hago cuando un cliente me paga?', k: '!cliente liquido pago cobro confirmar si no atrasado aviso pendiente', a: ['El día de pago te aparece en **Inicio > Pendiente** la pregunta "¿X ya liquidó su pago?".', '**Sí**: se abre una hoja con el monto prellenado; lo confirmas (o lo ajustas) y se registra el ingreso y se reparte tu dinero según tu plan.', '**No**: se marca como atrasado y la app te lo sigue recordando hasta que llegue.', 'También puedes decirme aquí: "me pagó Luis 1800" y lo registro con tu confirmación.'] },
    { id: 'tarjeta-add', g: 'app', t: '¿Cómo agrego una tarjeta de crédito?', k: '!tarjeta !tarjetas agregar crear nueva registrar anadir credito', a: ['Ve a **Pagos > Tarjetas > Agregar**.', 'Llena: banco, **fecha de corte**, **fecha límite de pago**, **pago para no generar intereses**, pago mínimo, saldo actual, límite, tasa de interés anual, CAT y anualidad.', 'Con eso la app aparta primero lo necesario para no generar intereses y te avisa del corte y del vencimiento.', 'Lo más importante es la fecha límite y el pago para no generar intereses; lo demás ayuda a calcular intereses estimados.'] },
    { id: 'prestamo-add', g: 'app', t: '¿Cómo agrego un préstamo?', k: '!prestamo !prestamos agregar crear nuevo registrar credito', a: ['Ve a **Pagos > Préstamos > Agregar**: pon el pago mensual, el día de pago y, si quieres, el saldo pendiente, la tasa y el CAT.', 'La app aparta para el préstamo después de tarjetas y herramientas de trabajo.'] },
    { id: 'sub-add', g: 'app', t: '¿Cómo agrego una suscripción?', k: '!suscripcion !suscripciones agregar crear nueva registrar herramienta trabajo logo icono capcut adobe', a: ['Ve a **Pagos > Suscripciones > Agregar**: nombre, monto exacto en pesos (como te lo cobran), día de cobro y una nota del plan.', 'Puedes poner una inicial, un emoji o **subir el logo**.', 'Marca **Herramienta de trabajo** si la necesitas para producir: se aparta antes que préstamos y servicios.'] },
    { id: 'servicio-add', g: 'app', t: '¿Cómo agrego la renta o un servicio?', k: '!renta !servicio !servicios luz internet agua agregar crear telefono', a: ['Ve a **Pagos > Servicios > Agregar**: detalle (renta, luz, internet), monto y día de pago. Se aparta después de tarjetas, herramientas y préstamos.'] },
    { id: 'pagado', g: 'app', t: '¿Cómo marco algo como pagado?', k: '!pagado !pague marcar pagar liquidar ya deuda tarjeta suscripcion', a: ['En **Pagos** toca **Marcar pagado** en la tarjeta de la deuda, o **Ya pagué** en el aviso de Inicio. Confirma el monto y la fecha.', 'Al pagar, la app empieza a apartar para el mes siguiente.', 'También me puedes decir "pagué Magnific" y lo registro con tu confirmación.'] },
    { id: 'deuda-edit', g: 'app', t: '¿Cómo edito, pauso o elimino un pago?', k: '!pausar !editar !eliminar borrar quitar cancelar deuda tarjeta suscripcion prestamo cambiar monto', a: ['En **Pagos** toca **Editar** en la tarjeta. Abajo tienes **Pausar (ya no lo pago)** y **Eliminar**.', 'Si cancelaste una suscripción, pausarla evita que la app siga apartando para ella.'] },
    { id: 'gasto-add', g: 'app', t: '¿Cómo registro un gasto?', k: '!gasto !gastos registrar agregar capturar anotar nuevo gasolina comida', a: ['Toca el **+** rojo de abajo y elige **Gasto**: monto con centavos, categoría, lugar, fecha y nota.', 'Atajo: dime aquí "gasté 350 en gasolina en Pemex" y lo registro cuando confirmes.'] },
    { id: 'ticket', g: 'app', t: '¿Cómo uso la foto de ticket?', k: '!ticket !foto !tickets camara galeria recibo escanear leer ocr', a: ['Toca **+ > Foto de ticket**. Puedes tomar la foto o elegir una de tu galería.', 'La app intenta proponerte monto, lugar y categoría (necesita internet la primera vez para esa lectura). Siempre revísalos antes de guardar.', 'Si no tienes tiempo, usa **Guardar pendiente** y lo completas después.'] },
    { id: 'ticket-pend', g: 'app', t: '¿Dónde completo un ticket pendiente?', k: '!pendiente !ticket completar guardado despues falta monto', a: ['Los tickets pendientes aparecen en **Calendario** el día en que los guardaste como "Ticket por completar". Tócalo, escribe monto y lugar y guarda.'] },
    { id: 'ingreso-add', g: 'app', t: '¿Cómo registro un ingreso?', k: '!ingreso !ingresos registrar agregar cobro recibi cobre deposito pago', a: ['Toca **+ > Ingreso**: monto, cliente (o "Otro ingreso"), fecha y nota.', 'Al guardar, la app te muestra el **reparto**: cuánto va a ahorro, a cada pago y a gastos de la semana, y cuánto queda libre.', 'Atajo: dime "me pagó Luis 1800".'] },
    { id: 'reparto', g: 'app', t: '¿Qué es el reparto de un ingreso?', k: '!reparto repartir apartar apartado distribuye dividir ahorro como se reparte', a: ['Cada ingreso se divide en este orden: **ahorro** (según tu plan), luego **pagos** (tarjetas, herramientas de trabajo, préstamos, servicios; por fecha), luego **gastos de la semana**, y lo que sobra queda **libre**.', 'Es solo organización: no mueve dinero real. Tú separas ese dinero en tu banco o efectivo.', 'Si te equivocaste, usa **Deshacer reparto** al terminar.'] },
    { id: 'deshacer', g: 'app', t: '¿Cómo deshago un reparto o ingreso?', k: '!deshacer reparto eliminar ingreso borrar equivoque corregir quitar', a: ['Justo después de registrar el ingreso toca **Deshacer reparto**. Más tarde, abre el ingreso en el **Calendario** y usa **Eliminar**: también quita los apartados que generó.'] },
    { id: 'planes', g: 'app', t: '¿Qué diferencia hay entre los planes?', k: '!plan !planes rapido equilibrado liquidez diferencia elegir cual', a: ['**Rápido** (deudas primero): aparta más y más pronto para liquidar rápido; te deja menos dinero libre. Ahorro sugerido 5%.', '**Equilibrado**: reparte cada pago en partes iguales hasta su fecha. Ahorro 10%.', '**Liquidez**: aparta solo lo necesario para llegar a cada fecha; máximo dinero libre. Ahorro 15%.', 'Los porcentajes de ahorro se pueden cambiar. Te recomiendo uno según tus números: pregúntame "¿qué plan me conviene?".'] },
    { id: 'plan-cambiar', g: 'app', t: '¿Cómo elijo o cambio mi plan del mes?', k: '!plan elegir cambiar mes ahorro porcentaje', a: ['En **Inicio** toca **Elegir/Cambiar** en la tarjeta del plan, o ve a **Ajustes > Plan del mes**. Ahí eliges el plan y editas el % de ahorro de cada uno.', 'Cada mes la app te pide elegir. También puedo hacerlo por ti: "elige el plan equilibrado".'] },
    { id: 'apartados', g: 'app', t: '¿Qué son los apartados, Libre y Apartado?', k: '!apartado !apartados libre significa saldo balance que quiere decir', a: ['**Balance** = el dinero que tienes hoy. **Apartado** = la parte ya reservada para pagos y ahorro. **Libre** = lo que queda para gastar sin descuidar nada.', 'Libre = Balance - Apartado.'] },
    { id: 'widgets', g: 'app', t: '¿Qué muestran las gráficas de Inicio?', k: '!grafica !graficas widget widgets inicio carrusel deslizar balance donut barras', a: ['Desliza el carrusel de Inicio: **Balance del mes** (línea real y proyección punteada, arrástrala con el dedo), **Avance de apartados**, **Gastos por categoría**, **Ingresos vs gastos por semana**, **Fondo de ahorro** y **Gasto por lugar**.'] },
    { id: 'calendario', g: 'app', t: '¿Cómo funciona el calendario?', k: '!calendario puntos colores dia lista filtros buscar movimientos', a: ['Los puntos: verde = ingreso, morado = gasto, naranja = pago o vencimiento, círculo = cobro esperado de cliente.', 'Toca un día para ver su detalle y agregar movimientos. Cambia a **Lista** para buscar por lugar, nota o cliente y filtrar por categoría y fechas.'] },
    { id: 'categorias', g: 'app', t: '¿Cómo creo categorías y presupuestos por semana?', k: '!categoria !categorias presupuesto limite semanal crear nueva', a: ['**Ajustes > Categorías y presupuesto**: ahí fijas el límite semanal de cada categoría y creas nuevas (nombre, color y límite opcional). En Inicio, "Esta semana" te muestra cuánto llevas contra cada límite.', 'También puedo hacerlo: "crea la categoría Mascotas con límite 300".'] },
    { id: 'gastos-semana', g: 'app', t: '¿Para qué sirve "Gastos de la semana"?', k: '!gastos semana promedio gasolina comida estimado reserva', a: ['En **Ajustes > Gastos de la semana** pones cuánto gastas normalmente en gasolina y comida. La app lo reserva en cada reparto. Cuando tienes varios gastos registrados, usa tu promedio real de las últimas 4 semanas.'] },
    { id: 'saldo', g: 'app', t: '¿Cómo corrijo mi saldo?', k: '!saldo corregir dinero tengo hoy cambiar ajustar inicial balance', a: ['**Ajustes > Saldo disponible**: escribe el dinero que tienes hoy. Es solo tu referencia, no se conecta a ningún banco.'] },
    { id: 'ics', g: 'app', t: '¿Cómo activo los recordatorios en el iPhone?', k: '!recordatorio !recordatorios notificacion notificaciones avisos calendario ics alarma push', a: ['Ve a **Ajustes > Recordatorios en el iPhone > Generar recordatorios**. Se crea un archivo para tu app Calendario con: plan el día 1 a las 7:00 am, cada pago (aviso un día antes y el mismo día), cortes de tarjeta y avisos de clientes ("mañana paga" 7 pm, "hoy paga" 7 am).', 'Si agregas o cambias pagos o clientes, genera el archivo de nuevo.', 'Notas: esta app no puede mandar notificaciones push por sí sola; por eso usa tu Calendario. Dentro de la app los avisos salen en **Inicio > Pendiente**.'] },
    { id: 'respaldo', g: 'app', t: '¿Cómo hago un respaldo o paso mis datos a otro iPhone?', k: '!respaldo !exportar !importar backup copia seguridad cambiar telefono nuevo iphone pasar datos', a: ['**Ajustes > Respaldo > Exportar respaldo** guarda un archivo con todos tus datos (guárdalo en Archivos o iCloud). Para recuperarlos o pasarlos a otro iPhone: instala la app ahí y usa **Importar respaldo**.', 'Haz un respaldo seguido, sobre todo antes de borrar datos de Safari o cambiar de teléfono.'] },
    { id: 'pin', g: 'app', t: '¿Cómo cambio o recupero mi PIN?', k: '!pin cambiar olvide olvidar contrasena recuperar codigo bloqueo seguridad', a: ['Para cambiarlo: **Ajustes > Cambiar PIN**.', 'La app se bloquea sola si pasa más de un minuto fuera de ella.', 'Si olvidas el PIN no hay forma de recuperarlo (así protege tu dinero): la única salida es "¿Olvidaste tu PIN?", que **borra todos los datos**. Por eso conviene tener respaldo.'] },
    { id: 'tema', g: 'app', t: '¿Cómo cambio entre modo claro y oscuro?', k: '!tema !oscuro !claro modo automatico apariencia dark', a: ['**Ajustes > Apariencia**: Claro, Oscuro o Automático (sigue el modo de tu iPhone).'] },
    { id: 'instalar', g: 'app', t: '¿Cómo instalo la app en el iPhone?', k: '!instalar pantalla inicio agregar icono safari como instalo', a: ['Abre el link en **Safari**, toca Compartir (cuadro con flecha), **Agregar a pantalla de inicio** y **Agregar**. Ábrela desde ese ícono.'] },
    { id: 'actualizar', g: 'app', t: '¿Cómo actualizo la app?', k: '!actualizar actualizacion version nueva no se actualiza cambios no aparecen', a: ['Sube los archivos nuevos a tu repositorio de GitHub (Add file > Upload files > Commit). Espera 1 o 2 minutos y abre la app **dos veces**: la primera descarga la versión nueva y la segunda ya la muestra. Tus datos no se borran.'] },
    { id: 'offline', g: 'app', t: '¿Funciona sin internet?', k: '!internet offline conexion sin wifi datos funciona', a: ['Sí. Después de abrirla una vez con internet, todo funciona sin conexión. Solo necesitan internet la primera descarga de la tipografía y la lectura automática de tickets.'] },
    { id: 'privacidad', g: 'app', t: '¿Dónde se guardan mis datos? ¿Son privados?', k: '!privacidad !privados datos guardan seguro seguridad donde nube servidor', a: ['Todo se guarda **solo en tu iPhone** (en Safari/app instalada). No hay cuenta, ni servidor, ni nube. Este asesor también funciona dentro de tu teléfono, sin enviar tus números a ningún lado.', 'La contrapartida: si borras los datos del sitio en Safari o desinstalas la app, se pierden. Haz respaldos.'] },
    { id: 'borrar', g: 'app', t: '¿Cómo borro todos mis datos?', k: '!borrar todo datos resetear reiniciar empezar de nuevo limpiar', a: ['**Ajustes > Borrar todos los datos**. Elimina clientes, pagos, gastos y fotos. No se puede deshacer; exporta un respaldo antes si lo dudas.'] },
    { id: 'fondo-usar', g: 'app', t: '¿Cómo uso mi fondo de ahorro?', k: '!fondo ahorro usar retirar sacar emergencia', a: ['En Inicio, en el widget **Fondo de ahorro**, toca **Usar del fondo** y escribe cuánto retiras. Úsalo solo para emergencias reales.'] },
    { id: 'falta', g: 'app', t: '¿Qué significa "faltan" o "no alcanzó"?', k: '!faltan !alcanzo no alcanzo shortfall falta dinero reparto insuficiente', a: ['Significa que el ingreso no cubrió lo que ese pago necesitaba hasta ahora. Se reporta para que lo sepas a tiempo. La app prioriza tarjetas, luego herramientas de trabajo, préstamos y servicios.', 'Pregúntame "¿cómo le hago para pagar todo?" y te armo una estrategia con montos.'] },
    { id: 'problemas', g: 'app', t: 'Mis datos desaparecieron / la app no abre', k: '!desaparecieron perdi datos error falla no abre no carga pantalla blanca problema bug', a: ['Si la pantalla sale en blanco, cierra la app por completo y ábrela otra vez con internet. Si los datos desaparecieron, probablemente se borraron los datos del sitio en Safari: usa **Ajustes > Respaldo > Importar**.', 'Si es otro problema, cuéntame exactamente qué pasa y en qué pantalla.'] },
    { id: 'asesor', g: 'app', t: '¿Qué puede hacer el asesor?', k: '!asesor ayuda comandos puedes hacer capacidades como funcionas', a: ['**Responder:** cuánto apartar, si te alcanza, qué pagar primero, cuánto puedes gastar, estadísticas y hallazgos, finanzas en general, impuestos y cómo usar la app.', '**Hacer (con tu confirmación):** registrar gastos e ingresos, marcar pagos, cambiar el orden de prioridad, crear categorías, cambiar % de ahorro, pausar pagos y elegir plan.', '**Recordar:** "recuerda que..." y preferencias como "respóndeme corto".', 'Toca **Temas** para ver ejemplos.'] },

    /* ===== FINANZAS EN GENERAL ===== */
    { id: 'cat', g: 'fin', t: '¿Qué es el CAT?', k: '!cat costo anual total que es significa', a: ['El **CAT** (Costo Anual Total) resume en un solo porcentaje cuánto te cuesta un crédito al año: intereses, comisiones y otros cargos. Sirve para comparar créditos: a menor CAT, más barato. Se usa solo para comparar; no es lo que te cobran cada mes.'] },
    { id: 'compuesto', g: 'fin', t: '¿Qué es el interés compuesto?', k: '!compuesto !compuesto interes sobre intereses crece bola nieve', a: ['Es cuando los intereses se suman al saldo y el siguiente interés se calcula sobre el total (intereses sobre intereses).', 'En una **deuda** juega en tu contra: si solo pagas el mínimo, el saldo casi no baja. En una **inversión** o ahorro juega a tu favor: mientras más tiempo, más crece. Por eso conviene pagar deudas caras primero y empezar a ahorrar temprano, aunque sea poco.'] },
    { id: 'tasa', g: 'fin', t: '¿Qué es la tasa de interés anual?', k: '!tasa !interes !intereses anual ordinaria que es significa porcentaje', a: ['Es el porcentaje que el banco cobra por prestarte dinero durante un año. En tarjetas suele dividirse entre 12 para el cobro mensual sobre tu saldo, más IVA sobre los intereses. Es solo una parte del costo; por eso se compara con el CAT.'] },
    { id: 'pago-min', g: 'fin', t: 'Pago mínimo vs pago para no generar intereses', k: '!minimo !intereses pago no generar total saldo diferencia pagar solo minimo', a: ['**Pago mínimo**: lo menos que debes pagar para no caer en mora. Si pagas solo eso, el resto del saldo genera intereses y tu deuda baja muy lento.', '**Pago para no generar intereses**: lo que debes pagar antes de la fecha límite para que no te cobren intereses ese periodo.', 'Si puedes, paga siempre este último. Si pagas solo el mínimo, la app te estima los intereses del mes.'] },
    { id: 'corte', g: 'fin', t: 'Fecha de corte vs fecha límite de pago', k: '!corte !limite fecha diferencia estado cuenta cuando pagar', a: ['La **fecha de corte** es el día en que se cierra tu estado de cuenta: lo gastado hasta ahí se suma. La **fecha límite de pago** llega unos días después; si pagas antes de esa fecha lo indicado, no hay intereses.', 'Truco: comprar justo después del corte te da más días para pagar sin intereses.'] },
    { id: 'anualidad', g: 'fin', t: '¿Qué es la anualidad de una tarjeta?', k: '!anualidad comision cuota anual tarjeta cobra', a: ['Es el cobro anual por tener la tarjeta. Algunas se pueden negociar o eliminar si la usas con regularidad, o cambiarte a una sin anualidad. Regístrala en la tarjeta para incluirla en tus cálculos.'] },
    { id: 'moratorio', g: 'fin', t: '¿Qué pasa si me atraso en un pago?', k: '!atraso atrasarme moratorio mora retraso tarde no pagar buro comision', a: ['Pagar tarde suele generar comisión por pago tardío e intereses moratorios, y puede afectar tu historial en Buró de Crédito. Si vas a atrasarte, paga al menos el mínimo a tiempo y habla con el banco para negociar.', 'Prioriza siempre tarjetas: es lo más caro de atrasar.'] },
    { id: 'utilizacion', g: 'fin', t: '¿Qué es la utilización de crédito?', k: '!utilizacion credito limite porcentaje buro score historial', a: ['Es qué porcentaje de tu límite estás usando (saldo ÷ límite). Mantenerlo abajo de ~30% suele ayudar a tu historial crediticio; arriba de 70% suele verse mal y encarece tu riesgo.'] },
    { id: 'emergencia', g: 'fin', t: '¿Qué es un fondo de emergencia y cuánto debo tener?', k: '!fondo !emergencia emergencias cuanto debo tener meses colchon', a: ['Es dinero apartado solo para imprevistos (enfermedad, falla del carro, mes sin clientes). La regla común: de **3 a 6 meses de gastos básicos**. Si tus ingresos son variables (freelance), apunta a 6.', 'Empieza chico: aunque sea 1 mes de gastos, y sube poco a poco con el % de ahorro de cada ingreso.'] },
    { id: 'avalancha', g: 'fin', t: 'Avalancha vs bola de nieve para pagar deudas', k: '!avalancha !nieve metodo estrategia pagar deudas salir orden', a: ['**Avalancha**: pagas primero la deuda con la tasa más alta (mínimo a las demás). Es la que menos intereses te cuesta.', '**Bola de nieve**: pagas primero la de menor saldo para liquidarla rápido; motiva, pero cuesta un poco más.', 'Los dos funcionan: elige el que no abandones. Si quieres, te digo cuál te conviene con tus tarjetas: "dame una estrategia".'] },
    { id: '50-30-20', g: 'fin', t: '¿Qué es la regla 50/30/20?', k: '!regla 50 30 20 presupuesto necesidades gustos ahorro', a: ['Una guía: **50%** necesidades (renta, comida, pagos), **30%** gustos, **20%** ahorro y deudas extra. Con ingresos variables sirve más como referencia que como regla exacta. Tus planes de la app son una versión práctica de esto.'] },
    { id: 'base-cero', g: 'fin', t: '¿Qué es un presupuesto base cero?', k: '!presupuesto cero base asignar cada peso planear', a: ['Es asignar un destino a cada peso que entra (ahorro, pagos, gastos, gustos) hasta que "sobran cero". Es justo lo que hace el reparto de cada ingreso en esta app.'] },
    { id: 'pagate-primero', g: 'fin', t: '¿Qué significa "págate primero"?', k: '!pagate primero ahorro automatico ahorrar antes', a: ['Ahorrar apenas llega el dinero, antes de gastar, en lugar de ahorrar "lo que sobre". En la app el ahorro es la primera línea de cada reparto.'] },
    { id: 'msi', g: 'fin', t: '¿Qué son los meses sin intereses?', k: '!msi !meses intereses sin comprar plazos', a: ['Pagas una compra en mensualidades iguales sin cargo extra. Úsalos solo si ya cuentas con el dinero y la mensualidad cabe en tu plan: son compromisos fijos que le quitan margen a tus ingresos futuros. Regístralos como pago mensual en Pagos.'] },
    { id: 'consolidar', g: 'fin', t: '¿Me conviene consolidar mis deudas?', k: '!consolidar !consolidacion unir deudas prestamo juntar refinanciar', a: ['Puede convenir si el nuevo crédito tiene un **CAT menor** al promedio de tus deudas y no te cobran comisiones altas. Compara CAT con CAT y calcula el costo total. No conviene si seguirás usando las tarjetas y volverás a endeudarte.'] },
    { id: 'salir-deudas', g: 'fin', t: '¿Cómo salgo de deudas?', k: '!deudas salir endeudado endeudamiento como pagar deuda', a: ['1) Deja de usar la tarjeta para gasto corriente. 2) Paga siempre al menos el mínimo a tiempo. 3) Ataca primero la deuda más cara (avalancha) o la más chica (bola de nieve). 4) Arma un mini fondo de emergencia para no endeudarte por imprevistos. 5) Revisa si puedes negociar tasa o consolidar.', 'Con tus datos te armo un plan con montos: "dame una estrategia".'] },
    { id: 'condusef', g: 'fin', t: '¿Qué hago ante cobros indebidos del banco?', k: '!condusef !reclamo cobro indebido banco queja aclaracion fraude cargo', a: ['Primero pide una aclaración al banco por escrito. Si no resuelven, puedes acudir a la **CONDUSEF**, que orienta y media entre usuarios y instituciones financieras. Guarda tus estados de cuenta y comprobantes.'] },
    { id: 'cetes', g: 'fin', t: '¿Dónde puedo ahorrar o invertir mi dinero?', k: '!invertir !inversion cetes ahorrar rendimiento cuenta banco donde', a: ['Para tu fondo de emergencia busca opciones **seguras y con liquidez** (que puedas retirar rápido), como cuentas de ahorro de rendimiento o instrumentos de bajo riesgo como CETES. Las tasas cambian; revisa la actual en la página oficial o en tu banco. Invertir en cosas de riesgo conviene hasta tener el colchón y las deudas caras bajo control.'] },
    { id: 'aguinaldo', g: 'fin', t: '¿Qué hago con el aguinaldo o un ingreso extra?', k: '!aguinaldo extra bono ingreso inesperado premio que hago', a: ['Una buena división: primero cubre deudas caras (tarjetas), luego completa tu fondo de emergencia y deja una parte para gustos. Para registrarlo, usa **+ > Ingreso** y la app te reparte según tu plan; con el plan **Rápido** destina más a liquidar.'] },
    { id: 'inflacion', g: 'fin', t: '¿Qué es la inflación?', k: '!inflacion precios suben poder adquisitivo que es', a: ['Es el aumento general de precios: con el tiempo tu dinero compra menos. Por eso conviene que tus ahorros de largo plazo rindan al menos algo cercano a la inflación y que revises tus tarifas y gastos fijos cada cierto tiempo.'] },
    { id: 'gastos-hormiga', g: 'fin', t: '¿Qué son los gastos hormiga?', k: '!hormiga gastos pequenos antojos cafe diarios fugas', a: ['Son gastos pequeños y frecuentes (cafés, antojos, comisiones, suscripciones olvidadas) que sumados pesan. Anota el lugar de cada gasto: en Inicio, "Gasto por lugar" te muestra dónde se va más. Pregúntame "¿en qué gasto de más?" y los analizo.'] },

    /* ===== FREELANCE E IMPUESTOS ===== */
    { id: 'irregular', g: 'free', t: 'Mis ingresos son irregulares, ¿cómo me organizo?', k: '!irregular !irregulares variables ingresos freelance cambian mes flujo organizar', a: ['1) Calcula tus gastos fijos mensuales (pagos + básicos): esa es tu **línea base**. 2) En meses buenos aparta el excedente a tu colchón. 3) Págate un "sueldo" estable desde ese colchón en meses flojos. 4) Aparta antes de gastar: justo lo que hace el reparto de cada cobro.', 'Elige el plan **Liquidez** en meses flojos y **Rápido** en meses fuertes.'] },
    { id: 'impuestos', g: 'free', t: '¿Cuánto debo apartar para impuestos?', k: '!impuestos !impuesto sat isr !apartar porcentaje declarar pagar hacienda', a: ['Depende de tu régimen y tus deducciones, así que no hay un número único. Como referencia, muchos freelancers apartan entre **10% y 30%** de lo que cobran hasta confirmarlo con su contador. Es mejor apartar de más y que sobre.', 'Para crear la costumbre: sube tu % de ahorro y llama a una parte "impuestos", o crea una categoría. Esta es información general, no asesoría fiscal: confirma con un contador o con el SAT.'] },
    { id: 'isr-iva', g: 'free', t: '¿Qué son el ISR y el IVA?', k: '!isr !iva impuesto sobre renta valor agregado diferencia que es', a: ['**ISR**: impuesto sobre tu ganancia (ingresos menos gastos deducibles, según tu régimen). **IVA**: impuesto al consumo; normalmente lo cobras a tus clientes (16%) y lo entregas al SAT, descontando el IVA de tus gastos deducibles.', 'Las reglas y tasas cambian: confirma con un contador o en sat.gob.mx.'] },
    { id: 'resico', g: 'free', t: '¿Qué es RESICO?', k: '!resico regimen simplificado confianza sat personas fisicas regimen', a: ['RESICO es un régimen fiscal simplificado del SAT para personas físicas con ingresos dentro de cierto límite, con tasas bajas de ISR sobre lo que **cobras**. Los topes y tasas cambian; revisa si aplicas con un contador o en el portal del SAT. Muchos freelancers lo consideran por su simplicidad.'] },
    { id: 'factura', g: 'free', t: '¿Necesito facturar a mis clientes?', k: '!factura !facturar cfdi rfc comprobante fiscal cliente emitir', a: ['Si estás dado de alta ante el SAT, debes emitir **CFDI** (factura) por lo que cobras cuando el cliente lo pida o lo requieras fiscalmente. También sirve para que tus clientes deduzcan tu servicio. Pregunta a tu contador cómo aplicarlo en tu caso.'] },
    { id: 'deducibles', g: 'free', t: '¿Mis herramientas de trabajo son deducibles?', k: '!deducible !deducibles herramientas software suscripciones gastos negocio deducir equipo', a: ['En general, gastos **estrictamente indispensables** para tu actividad (software, equipo, internet) pueden deducirse **si cuentan con factura a tu nombre** y cumplen requisitos. Pide factura en cada pago y consúltalo con tu contador. En la app marca esas suscripciones como "herramienta de trabajo".'] },
    { id: 'cobrar', g: 'free', t: '¿Cómo cobro a tiempo a mis clientes?', k: '!cobrar !cobro clientes pagan tarde anticipo moroso recordatorio cobranza', a: ['Pide **anticipo** (30% a 50%) antes de empezar, pon fechas de pago por escrito, envía recordatorio un día antes (la app te avisa "mañana paga") y no entregues el final sin liquidar. Si un cliente se atrasa, márcalo "No" en la app para seguirle la pista.'] },
    { id: 'tarifa', g: 'free', t: '¿Cómo calculo cuánto cobrar?', k: '!tarifa !precio cobrar cuanto cotizar hora proyecto precios servicio', a: ['Suma tus gastos fijos mensuales + impuestos + ahorro + una ganancia, y divídelo entre las horas o proyectos que realmente puedes vender al mes (no todas son facturables). Eso te da tu **tarifa mínima**; por debajo de eso pierdes dinero.'] },
    { id: 'cuentas', g: 'free', t: '¿Separo mi dinero personal y el del negocio?', k: '!separar cuenta cuentas personal negocio mezclar bancaria', a: ['Sí, conviene. Una cuenta para lo que cobras (negocio e impuestos) y otra personal, a la que te transfieres tu "sueldo". Facilita tu contabilidad y evita gastar lo que debes apartar.'] },
    { id: 'temporada', g: 'free', t: '¿Qué hago en temporada baja?', k: '!temporada baja mes flojo pocos clientes sin trabajo crisis', a: ['Usa tu colchón, recorta gastos variables, pausa suscripciones que no uses y elige el plan **Liquidez**. Aprovecha para prospectar y cobrar pendientes. Pregúntame "¿me alcanza este mes?" para ver tus números.'] }
  ];

  NB.TOPICS = {
    dinero: { name: 'Mi dinero', qs: ['¿Cuánto aparto esta semana?', '¿Me alcanza este mes?', '¿Qué pago primero?', '¿Cuánto puedo gastar?', '¿Cuánto tendré a fin de mes?', 'Dime exactamente cuánto dar a cada cosa', '¿Cuántos meses de colchón tengo?'] },
    analisis: { name: 'Análisis', qs: ['Propón una meta de ahorro grande', '¿En qué gasto de más?', 'Analiza mis estadísticas', '¿Cuánto gasté en comida este mes?', '¿Qué clientes me deben?', 'Dame una estrategia para pagar todo', '¿Qué plan me conviene?'] },
    acciones: { name: 'Hacer cosas', qs: ['Gasté 350 en gasolina en Pemex', 'Me pagó Luis 1800', 'Pon CapCut antes que Adobe', 'Pagué Magnific', 'Crea la categoría Mascotas con límite 300', 'Cambia mi ahorro a 12%'] },
    app: { name: 'Usar la app', qs: ['¿Cómo agrego una tarjeta de crédito?', '¿Cómo registro un ingreso?', '¿Qué es el reparto de un ingreso?', '¿Cómo activo los recordatorios en el iPhone?', '¿Cómo hago un respaldo?', '¿Qué diferencia hay entre los planes?'] },
    fin: { name: 'Finanzas', qs: ['¿Qué es el CAT?', 'Pago mínimo vs pago para no generar intereses', 'Avalancha vs bola de nieve', '¿Qué es un fondo de emergencia?', '¿Cómo salgo de deudas?', '¿Qué es la utilización de crédito?'] },
    free: { name: 'Freelance', qs: ['¿Cuánto debo apartar para impuestos?', 'Mis ingresos son irregulares, ¿cómo me organizo?', '¿Qué es RESICO?', '¿Mis herramientas son deducibles?', '¿Cómo cobro a tiempo?', '¿Qué hago en temporada baja?'] }
  };
})();
